export const initialState = {
  page: "startPage",
  phoneNumber1: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  phoneNumber2: [
    { number: 0, locked: false },
    { number: 1, locked: false },
    { number: 2, locked: false },
    { number: 3, locked: false },
    { number: 4, locked: false },
    { number: 5, locked: false },
    { number: 6, locked: false },
    { number: 7, locked: false },
    { number: 8, locked: false },
    { number: 9, locked: false },
  ],
  phoneConfirmButtonClass: "phone-page-confirm-buttons",
  streetAddress: "",
  city: "",
  state: "",
  stateAbbreviation: "",
  stateCapital: "",
  stateLargest: "",
  stateAdmitted: "",
};
