export const usStates = [
  {
    key: "0",
    name: "Alabama",
    abbreviation: "AL",
    capitalCity: "Montgomery",
    largestCity: "Huntsville",
    admitted: "1819-12-14",
  },
  {
    key: "1",
    name: "Alaska",
    abbreviation: "AK",
    capitalCity: "Juneau",
    largestCity: "Anchorage",
    admitted: "1959-01-03",
  },
  {
    key: "2",
    name: "Arizona",
    abbreviation: "AZ",
    capitalCity: "Phoenix",
    largestCity: "Phoenix",
    admitted: "1912-02-14",
  },
  {
    key: "3",
    name: "Arkansas",
    abbreviation: "AR",
    capitalCity: "Little Rock",
    largestCity: "Little Rock",
    admitted: "1836-06-15	",
  },
  {
    key: "4",
    name: "California",
    abbreviation: "CA",
    capitalCity: "Sacramento",
    largestCity: "Los Angeles",
    admitted: "1850-09-09",
  },
  {
    key: "5",
    name: "Colorado",
    abbreviation: "CO",
    capitalCity: "Denver",
    largestCity: "Denver",
    admitted: "1876-08-01",
  },
  {
    key: "6",
    name: "Connecticut",
    abbreviation: "CT",
    capitalCity: "Hartford",
    largestCity: "Bridgeport",
    admitted: "1788-01-09",
  },
  {
    key: "7",
    name: "Delaware",
    abbreviation: "DE",
    capitalCity: "Dover",
    largestCity: "Wilmington",
    admitted: "1787-12-07",
  },
  {
    key: "8",
    name: "Florida",
    abbreviation: "FL",
    capitalCity: "Tallahassee",
    largestCity: "Jacksonville",
    admitted: "1845-03-03",
  },
  {
    key: "9",
    name: "Georgia",
    abbreviation: "GA",
    capitalCity: "Atlanta",
    largestCity: "Atlanta",
    admitted: "1788-01-02",
  },
  {
    key: "10",
    name: "Hawaii",
    abbreviation: "HI",
    capitalCity: "Honolulu",
    largestCity: "Honolulu",
    admitted: "1959-08-21",
  },
  {
    key: "11",
    name: "Idaho",
    abbreviation: "ID",
    capitalCity: "Boise",
    largestCity: "Boise",
    admitted: "1890-07-03",
  },
  {
    key: "12",
    name: "Illinois",
    abbreviation: "IL",
    capitalCity: "Springfield",
    largestCity: "Chicago",
    admitted: "1818-12-03",
  },
  {
    key: "13",
    name: "Indiana",
    abbreviation: "IN",
    capitalCity: "Indianapolis",
    largestCity: "Indianapolis",
    admitted: "1816-12-11",
  },
  {
    key: "14",
    name: "Iowa",
    abbreviation: "IA",
    capitalCity: "Des Moines",
    largestCity: "Des Moines",
    admitted: "1846-12-28",
  },
  {
    key: "15",
    name: "Kansas",
    abbreviation: "KS",
    capitalCity: "Topeka",
    largestCity: "Wichita",
    admitted: "1861-01-29",
  },
  {
    key: "16",
    name: "Kentucky",
    abbreviation: "KY",
    capitalCity: "Frankfort",
    largestCity: "Louisville",
    admitted: "1792-06-01",
  },
  {
    key: "17",
    name: "Louisiana",
    abbreviation: "LA",
    capitalCity: "Baton Rouge",
    largestCity: "New Orleans",
    admitted: "1812-04-30",
  },
  {
    key: "18",
    name: "Maine",
    abbreviation: "ME",
    capitalCity: "Augusta",
    largestCity: "Portland",
    admitted: "1820-03-15",
  },
  {
    key: "19",
    name: "Maryland",
    abbreviation: "MD",
    capitalCity: "Annapolis",
    largestCity: "Baltimore",
    admitted: "1788-04-28",
  },
  {
    key: "20",
    name: "Massachusetts",
    abbreviation: "MA",
    capitalCity: "Boston",
    largestCity: "Boston",
    admitted: "1788-02-06",
  },
  {
    key: "21",
    name: "Michigan",
    abbreviation: "MI",
    capitalCity: "Lansing",
    largestCity: "Detroit",
    admitted: "1837-01-26",
  },
  {
    key: "22",
    name: "Minnesota",
    abbreviation: "MN",
    capitalCity: "Saint Paul",
    largestCity: "Minneapolis",
    admitted: "1858-05-11",
  },
  {
    key: "23",
    name: "Mississippi",
    abbreviation: "MS",
    capitalCity: "Jackson",
    largestCity: "Jackson",
    admitted: "1817-12-10",
  },
  {
    key: "24",
    name: "Missouri",
    abbreviation: "MO",
    capitalCity: "Jefferson City",
    largestCity: "Kansas City",
    admitted: "1821-08-10",
  },
  {
    key: "25",
    name: "Montana",
    abbreviation: "MT",
    capitalCity: "Helena",
    largestCity: "Billings",
    admitted: "1889-11-08",
  },
  {
    key: "26",
    name: "Nebraska",
    abbreviation: "NE",
    capitalCity: "Lincoln",
    largestCity: "Omaha",
    admitted: "1867-03-01",
  },
  {
    key: "27",
    name: "Nevada",
    abbreviation: "NV",
    capitalCity: "Carson City",
    largestCity: "Las Vegas",
    admitted: "1864-10-31",
  },
  {
    key: "28",
    name: "New Hampshire",
    abbreviation: "NH",
    capitalCity: "Concord",
    largestCity: "Manchester",
    admitted: "1788-06-21",
  },
  {
    key: "29",
    name: "New Jersey",
    abbreviation: "NJ",
    capitalCity: "Trenton",
    largestCity: "Newark",
    admitted: "1787-12-18",
  },
  {
    key: "30",
    name: "New Mexico",
    abbreviation: "NM",
    capitalCity: "Santa Fe",
    largestCity: "Albuquerque",
    admitted: "1912-01-06",
  },
  {
    key: "31",
    name: "New York",
    abbreviation: "NY",
    capitalCity: "Albany",
    largestCity: "New York City",
    admitted: "1788-07-26",
  },
  {
    key: "32",
    name: "North Carolina",
    abbreviation: "NC",
    capitalCity: "Raleigh",
    largestCity: "Charlotte",
    admitted: "1789-11-21",
  },
  {
    key: "33",
    name: "North Dakota",
    abbreviation: "ND",
    capitalCity: "Bismarck",
    largestCity: "Fargo",
    admitted: "1889-11-02",
  },
  {
    key: "34",
    name: "Ohio",
    abbreviation: "OH",
    capitalCity: "Columbus",
    largestCity: "Columbus",
    admitted: "1803-03-01",
  },
  {
    key: "35",
    name: "Oklahoma",
    abbreviation: "OK",
    capitalCity: "Oklahoma City",
    largestCity: "Oklahoma City",
    admitted: "1907-11-16",
  },
  {
    key: "36",
    name: "Oregon",
    abbreviation: "OR",
    capitalCity: "Salem",
    largestCity: "Portland",
    admitted: "1859-02-14",
  },
  {
    key: "37",
    name: "Pennsylvania",
    abbreviation: "PA",
    capitalCity: "Harrisburg",
    largestCity: "Philadelphia",
    admitted: "1787-12-12",
  },
  {
    key: "38",
    name: "Rhode Island",
    abbreviation: "RI",
    capitalCity: "Providence",
    largestCity: "Providence",
    admitted: "1790-05-29",
  },
  {
    key: "39",
    name: "South Carolina",
    abbreviation: "SC",
    capitalCity: "Columbia",
    largestCity: "Columbia",
    admitted: "1788-05-23",
  },
  {
    key: "40",
    name: "South Dakota",
    abbreviation: "SD",
    capitalCity: "Pierre",
    largestCity: "Sioux Falls",
    admitted: "1889-11-02",
  },
  {
    key: "41",
    name: "Tennessee",
    abbreviation: "TN",
    capitalCity: "Nashville",
    largestCity: "Nashville",
    admitted: "1796-06-01",
  },
  {
    key: "42",
    name: "Texas",
    abbreviation: "TX",
    capitalCity: "Austin",
    largestCity: "Houston",
    admitted: "1845-12-29",
  },
  {
    key: "43",
    name: "Utah",
    abbreviation: "UT",
    capitalCity: "Salt Lake City",
    largestCity: "Salt Lake City",
    admitted: "1896-01-04",
  },
  {
    key: "44",
    name: "Vermont",
    abbreviation: "VT",
    capitalCity: "Montpelier",
    largestCity: "Burlington",
    admitted: "1791-11-04",
  },
  {
    key: "45",
    name: "Virginia",
    abbreviation: "VA",
    capitalCity: "Richmond",
    largestCity: "Virginia Beach",
    admitted: "1788-06-25",
  },
  {
    key: "46",
    name: "Washington",
    abbreviation: "WA",
    capitalCity: "Olympia",
    largestCity: "Seattle",
    admitted: "1889-11-11",
  },
  {
    key: "47",
    name: "West Virginia",
    abbreviation: "WV",
    capitalCity: "Charleston",
    largestCity: "Charleston",
    admitted: "1863-06-20",
  },
  {
    key: "48",
    name: "Wisconsin",
    abbreviation: "WI",
    capitalCity: "Madison",
    largestCity: "Milwaukee",
    admitted: "1848-05-29",
  },
  {
    key: "49",
    name: "Wyoming",
    abbreviation: "WY",
    capitalCity: "Cheyenne",
    largestCity: "Cheyenne",
    admitted: "1890-07-10",
  },
];
